### ISSUE TITLE
help build on alpine linux v3.15

### ISSUE THREAD

**Issue by bit4bit** [rcaelers/workrave#408]
**Describe the bug**
hi, i trying to compile workrave 1.10.50  on alpine linux v3.15, but throws

<pre>
libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I../.. -W "-DWORKRAVE_PKGDATADIR=\"/usr/share/workrave\"" "-DWORKRAVE_DATADIR=\"/usr/share\"" -D_XOPEN_SOURCE=600 -I../../common/include -I../../libs/dbus/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -Wno-cast-function-type -g -O2 -MT Locale.lo -MD -MP -MF .deps/Locale.Tpo -c Locale.cc  -fPIC -DPIC -o .libs/Locale.o
Locale.cc: In static member function 'static int Locale::get_week_start()':
Locale.cc:266:33: error: '_NL_TIME_FIRST_WEEKDAY' was not declared in this scope
  266 |   langinfo.string = nl_langinfo(_NL_TIME_FIRST_WEEKDAY);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
Locale.cc:268:33: error: '_NL_TIME_WEEK_1STDAY' was not declared in this scope
  268 |   langinfo.string = nl_langinfo(_NL_TIME_WEEK_1STDAY);
      |                                 ^~~~~~~~~~~~~~~~~~~~
</pre>

**To Reproduce**
1. download [source](https://github.com/rcaelers/workrave/releases/download/v1_10_50/workrave-v1.10.50.tar.gz)
2. install depends "apk add glib-dev gtkmm3-dev automake autoconf autoconf-archive py3-jinja2 intltool libtool libxscrnsaver-dev boost-dev gobject-introspection-dev libsm-dev libice-dev libxtst-dev libx11-dev"
3. run "./autogen.sh"
4. run "./configure"
5. run "make"

**Expected behavior**

finish build

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Alpine Linux
 - Distribution Version:  v3.15
 - Desktop Environment: i3wm
 - Workrave Version 1.10.50

**Additional context**

i fix with this but not know if it's correct.

<pre>
--- orig/workrave-1_10_50/common/src/Locale.cc
+++ workrave-1_10_50/common/src/Locale.cc
@@ -263,9 +263,9 @@
   gint first_weekday = 1;
   guint week_origin;
 
-  langinfo.string = nl_langinfo(_NL_TIME_FIRST_WEEKDAY);
+  langinfo.string = nl_langinfo(DAY_1);
   first_weekday = langinfo.string[0];
-  langinfo.string = nl_langinfo(_NL_TIME_WEEK_1STDAY);
+  langinfo.string = nl_langinfo(DAY_1);
   week_origin = langinfo.word;
   if (week_origin == 19971130) /* Sunday */
     week_1stday = 0;
</pre>

thanks for your help

**Comment by rcaelers** [comment]
Fixed in Workrave 1.11.
